/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1beta1 "sigs.k8s.io/nvidia-dra-driver-gpu/api/nvidia.com/resource/v1beta1"
	scheme "sigs.k8s.io/nvidia-dra-driver-gpu/pkg/nvidia.com/clientset/versioned/scheme"
)

// ComputeDomainCliquesGetter has a method to return a ComputeDomainCliqueInterface.
// A group's client should implement this interface.
type ComputeDomainCliquesGetter interface {
	ComputeDomainCliques(namespace string) ComputeDomainCliqueInterface
}

// ComputeDomainCliqueInterface has methods to work with ComputeDomainClique resources.
type ComputeDomainCliqueInterface interface {
	Create(ctx context.Context, computeDomainClique *v1beta1.ComputeDomainClique, opts v1.CreateOptions) (*v1beta1.ComputeDomainClique, error)
	Update(ctx context.Context, computeDomainClique *v1beta1.ComputeDomainClique, opts v1.UpdateOptions) (*v1beta1.ComputeDomainClique, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.ComputeDomainClique, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.ComputeDomainCliqueList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.ComputeDomainClique, err error)
	ComputeDomainCliqueExpansion
}

// computeDomainCliques implements ComputeDomainCliqueInterface
type computeDomainCliques struct {
	client rest.Interface
	ns     string
}

// newComputeDomainCliques returns a ComputeDomainCliques
func newComputeDomainCliques(c *ResourceV1beta1Client, namespace string) *computeDomainCliques {
	return &computeDomainCliques{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the computeDomainClique, and returns the corresponding computeDomainClique object, and an error if there is any.
func (c *computeDomainCliques) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.ComputeDomainClique, err error) {
	result = &v1beta1.ComputeDomainClique{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("computedomaincliques").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ComputeDomainCliques that match those selectors.
func (c *computeDomainCliques) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.ComputeDomainCliqueList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.ComputeDomainCliqueList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("computedomaincliques").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested computeDomainCliques.
func (c *computeDomainCliques) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("computedomaincliques").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a computeDomainClique and creates it.  Returns the server's representation of the computeDomainClique, and an error, if there is any.
func (c *computeDomainCliques) Create(ctx context.Context, computeDomainClique *v1beta1.ComputeDomainClique, opts v1.CreateOptions) (result *v1beta1.ComputeDomainClique, err error) {
	result = &v1beta1.ComputeDomainClique{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("computedomaincliques").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(computeDomainClique).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a computeDomainClique and updates it. Returns the server's representation of the computeDomainClique, and an error, if there is any.
func (c *computeDomainCliques) Update(ctx context.Context, computeDomainClique *v1beta1.ComputeDomainClique, opts v1.UpdateOptions) (result *v1beta1.ComputeDomainClique, err error) {
	result = &v1beta1.ComputeDomainClique{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("computedomaincliques").
		Name(computeDomainClique.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(computeDomainClique).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the computeDomainClique and deletes it. Returns an error if one occurs.
func (c *computeDomainCliques) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("computedomaincliques").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *computeDomainCliques) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("computedomaincliques").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched computeDomainClique.
func (c *computeDomainCliques) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.ComputeDomainClique, err error) {
	result = &v1beta1.ComputeDomainClique{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("computedomaincliques").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
