apiVersion: v1
kind: ServiceAccount
metadata:
  name: compute-domain-daemon-service-account
  namespace: {{ include "nvidia-dra-driver-gpu.namespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: compute-domain-daemon-role
  namespace: {{ include "nvidia-dra-driver-gpu.namespace" . }}
rules:
- apiGroups: ["resource.nvidia.com"]
  resources: ["computedomains", "computedomains/status"]
  verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: compute-domain-daemon-role-binding
  namespace: {{ include "nvidia-dra-driver-gpu.namespace" . }}
subjects:
- kind: ServiceAccount
  name: compute-domain-daemon-service-account
  namespace: {{ include "nvidia-dra-driver-gpu.namespace" . }}
roleRef:
  kind: ClusterRole
  name: compute-domain-daemon-role
  apiGroup: rbac.authorization.k8s.io 
