/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1beta1 "sigs.k8s.io/dra-driver-nvidia-gpu/api/nvidia.com/resource/v1beta1"
)

// FakeComputeDomainCliques implements ComputeDomainCliqueInterface
type FakeComputeDomainCliques struct {
	Fake *FakeResourceV1beta1
	ns   string
}

var computedomaincliquesResource = v1beta1.SchemeGroupVersion.WithResource("computedomaincliques")

var computedomaincliquesKind = v1beta1.SchemeGroupVersion.WithKind("ComputeDomainClique")

// Get takes name of the computeDomainClique, and returns the corresponding computeDomainClique object, and an error if there is any.
func (c *FakeComputeDomainCliques) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.ComputeDomainClique, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(computedomaincliquesResource, c.ns, name), &v1beta1.ComputeDomainClique{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ComputeDomainClique), err
}

// List takes label and field selectors, and returns the list of ComputeDomainCliques that match those selectors.
func (c *FakeComputeDomainCliques) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.ComputeDomainCliqueList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(computedomaincliquesResource, computedomaincliquesKind, c.ns, opts), &v1beta1.ComputeDomainCliqueList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.ComputeDomainCliqueList{ListMeta: obj.(*v1beta1.ComputeDomainCliqueList).ListMeta}
	for _, item := range obj.(*v1beta1.ComputeDomainCliqueList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested computeDomainCliques.
func (c *FakeComputeDomainCliques) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(computedomaincliquesResource, c.ns, opts))

}

// Create takes the representation of a computeDomainClique and creates it.  Returns the server's representation of the computeDomainClique, and an error, if there is any.
func (c *FakeComputeDomainCliques) Create(ctx context.Context, computeDomainClique *v1beta1.ComputeDomainClique, opts v1.CreateOptions) (result *v1beta1.ComputeDomainClique, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(computedomaincliquesResource, c.ns, computeDomainClique), &v1beta1.ComputeDomainClique{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ComputeDomainClique), err
}

// Update takes the representation of a computeDomainClique and updates it. Returns the server's representation of the computeDomainClique, and an error, if there is any.
func (c *FakeComputeDomainCliques) Update(ctx context.Context, computeDomainClique *v1beta1.ComputeDomainClique, opts v1.UpdateOptions) (result *v1beta1.ComputeDomainClique, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(computedomaincliquesResource, c.ns, computeDomainClique), &v1beta1.ComputeDomainClique{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ComputeDomainClique), err
}

// Delete takes name of the computeDomainClique and deletes it. Returns an error if one occurs.
func (c *FakeComputeDomainCliques) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(computedomaincliquesResource, c.ns, name, opts), &v1beta1.ComputeDomainClique{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeComputeDomainCliques) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(computedomaincliquesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.ComputeDomainCliqueList{})
	return err
}

// Patch applies the patch and returns the patched computeDomainClique.
func (c *FakeComputeDomainCliques) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.ComputeDomainClique, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(computedomaincliquesResource, c.ns, name, pt, data, subresources...), &v1beta1.ComputeDomainClique{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ComputeDomainClique), err
}
