apiVersion: v1
kind: Pod
metadata:
  name: fm-partition-pod
  labels:
    app: fm-partition-sample
spec:
  containers:
  - name: ctr
    image: nvidia/cuda:12.0.0-base-ubuntu22.04
    command: ["bash", "-c"]
    args:
    - sleep infinity
    resources:
      claims:
      - name: gpus
  resourceClaims:
  - name: gpus
    resourceClaimTemplateName: fm-partition-2gpu
