/*
 * Copyright (c) 2023, NVIDIA CORPORATION.  All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/NVIDIA/k8s-dra-driver/api/nvidia.com/resource/gpu/v1alpha1"
	scheme "github.com/NVIDIA/k8s-dra-driver/pkg/nvidia.com/resource/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// VfioDeviceClaimParametersesGetter has a method to return a VfioDeviceClaimParametersInterface.
// A group's client should implement this interface.
type VfioDeviceClaimParametersesGetter interface {
	VfioDeviceClaimParameterses(namespace string) VfioDeviceClaimParametersInterface
}

// VfioDeviceClaimParametersInterface has methods to work with VfioDeviceClaimParameters resources.
type VfioDeviceClaimParametersInterface interface {
	Create(ctx context.Context, vfioDeviceClaimParameters *v1alpha1.VfioDeviceClaimParameters, opts v1.CreateOptions) (*v1alpha1.VfioDeviceClaimParameters, error)
	Update(ctx context.Context, vfioDeviceClaimParameters *v1alpha1.VfioDeviceClaimParameters, opts v1.UpdateOptions) (*v1alpha1.VfioDeviceClaimParameters, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.VfioDeviceClaimParameters, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.VfioDeviceClaimParametersList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VfioDeviceClaimParameters, err error)
	VfioDeviceClaimParametersExpansion
}

// vfioDeviceClaimParameterses implements VfioDeviceClaimParametersInterface
type vfioDeviceClaimParameterses struct {
	client rest.Interface
	ns     string
}

// newVfioDeviceClaimParameterses returns a VfioDeviceClaimParameterses
func newVfioDeviceClaimParameterses(c *GpuV1alpha1Client, namespace string) *vfioDeviceClaimParameterses {
	return &vfioDeviceClaimParameterses{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the vfioDeviceClaimParameters, and returns the corresponding vfioDeviceClaimParameters object, and an error if there is any.
func (c *vfioDeviceClaimParameterses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VfioDeviceClaimParameters, err error) {
	result = &v1alpha1.VfioDeviceClaimParameters{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("vfiodeviceclaimparameterses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of VfioDeviceClaimParameterses that match those selectors.
func (c *vfioDeviceClaimParameterses) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VfioDeviceClaimParametersList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.VfioDeviceClaimParametersList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("vfiodeviceclaimparameterses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested vfioDeviceClaimParameterses.
func (c *vfioDeviceClaimParameterses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("vfiodeviceclaimparameterses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a vfioDeviceClaimParameters and creates it.  Returns the server's representation of the vfioDeviceClaimParameters, and an error, if there is any.
func (c *vfioDeviceClaimParameterses) Create(ctx context.Context, vfioDeviceClaimParameters *v1alpha1.VfioDeviceClaimParameters, opts v1.CreateOptions) (result *v1alpha1.VfioDeviceClaimParameters, err error) {
	result = &v1alpha1.VfioDeviceClaimParameters{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("vfiodeviceclaimparameterses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vfioDeviceClaimParameters).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a vfioDeviceClaimParameters and updates it. Returns the server's representation of the vfioDeviceClaimParameters, and an error, if there is any.
func (c *vfioDeviceClaimParameterses) Update(ctx context.Context, vfioDeviceClaimParameters *v1alpha1.VfioDeviceClaimParameters, opts v1.UpdateOptions) (result *v1alpha1.VfioDeviceClaimParameters, err error) {
	result = &v1alpha1.VfioDeviceClaimParameters{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("vfiodeviceclaimparameterses").
		Name(vfioDeviceClaimParameters.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vfioDeviceClaimParameters).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the vfioDeviceClaimParameters and deletes it. Returns an error if one occurs.
func (c *vfioDeviceClaimParameterses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("vfiodeviceclaimparameterses").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *vfioDeviceClaimParameterses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("vfiodeviceclaimparameterses").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched vfioDeviceClaimParameters.
func (c *vfioDeviceClaimParameterses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VfioDeviceClaimParameters, err error) {
	result = &v1alpha1.VfioDeviceClaimParameters{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("vfiodeviceclaimparameterses").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
