/*
 * Copyright (c) 2023, NVIDIA CORPORATION.  All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/NVIDIA/k8s-dra-driver/api/nvidia.com/resource/gpu/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVfioDeviceClaimParameterses implements VfioDeviceClaimParametersInterface
type FakeVfioDeviceClaimParameterses struct {
	Fake *FakeGpuV1alpha1
	ns   string
}

var vfiodeviceclaimparametersesResource = v1alpha1.SchemeGroupVersion.WithResource("vfiodeviceclaimparameterses")

var vfiodeviceclaimparametersesKind = v1alpha1.SchemeGroupVersion.WithKind("VfioDeviceClaimParameters")

// Get takes name of the vfioDeviceClaimParameters, and returns the corresponding vfioDeviceClaimParameters object, and an error if there is any.
func (c *FakeVfioDeviceClaimParameterses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VfioDeviceClaimParameters, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(vfiodeviceclaimparametersesResource, c.ns, name), &v1alpha1.VfioDeviceClaimParameters{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VfioDeviceClaimParameters), err
}

// List takes label and field selectors, and returns the list of VfioDeviceClaimParameterses that match those selectors.
func (c *FakeVfioDeviceClaimParameterses) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VfioDeviceClaimParametersList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(vfiodeviceclaimparametersesResource, vfiodeviceclaimparametersesKind, c.ns, opts), &v1alpha1.VfioDeviceClaimParametersList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.VfioDeviceClaimParametersList{ListMeta: obj.(*v1alpha1.VfioDeviceClaimParametersList).ListMeta}
	for _, item := range obj.(*v1alpha1.VfioDeviceClaimParametersList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested vfioDeviceClaimParameterses.
func (c *FakeVfioDeviceClaimParameterses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(vfiodeviceclaimparametersesResource, c.ns, opts))

}

// Create takes the representation of a vfioDeviceClaimParameters and creates it.  Returns the server's representation of the vfioDeviceClaimParameters, and an error, if there is any.
func (c *FakeVfioDeviceClaimParameterses) Create(ctx context.Context, vfioDeviceClaimParameters *v1alpha1.VfioDeviceClaimParameters, opts v1.CreateOptions) (result *v1alpha1.VfioDeviceClaimParameters, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(vfiodeviceclaimparametersesResource, c.ns, vfioDeviceClaimParameters), &v1alpha1.VfioDeviceClaimParameters{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VfioDeviceClaimParameters), err
}

// Update takes the representation of a vfioDeviceClaimParameters and updates it. Returns the server's representation of the vfioDeviceClaimParameters, and an error, if there is any.
func (c *FakeVfioDeviceClaimParameterses) Update(ctx context.Context, vfioDeviceClaimParameters *v1alpha1.VfioDeviceClaimParameters, opts v1.UpdateOptions) (result *v1alpha1.VfioDeviceClaimParameters, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(vfiodeviceclaimparametersesResource, c.ns, vfioDeviceClaimParameters), &v1alpha1.VfioDeviceClaimParameters{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VfioDeviceClaimParameters), err
}

// Delete takes name of the vfioDeviceClaimParameters and deletes it. Returns an error if one occurs.
func (c *FakeVfioDeviceClaimParameterses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(vfiodeviceclaimparametersesResource, c.ns, name, opts), &v1alpha1.VfioDeviceClaimParameters{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVfioDeviceClaimParameterses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(vfiodeviceclaimparametersesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.VfioDeviceClaimParametersList{})
	return err
}

// Patch applies the patch and returns the patched vfioDeviceClaimParameters.
func (c *FakeVfioDeviceClaimParameterses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VfioDeviceClaimParameters, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(vfiodeviceclaimparametersesResource, c.ns, name, pt, data, subresources...), &v1alpha1.VfioDeviceClaimParameters{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VfioDeviceClaimParameters), err
}
